# Generated by Django 3.0.3 on 2020-05-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200527_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_no',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
