# Generated by Django 3.0.3 on 2020-06-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200604_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, default=None,
                                   primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
