# Generated by Django 3.0.3 on 2020-06-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200604_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='eachquestion',
            old_name='correctOption',
            new_name='correctAns',
        ),
        migrations.RemoveField(
            model_name='eachquestion',
            name='question_name',
        ),
        migrations.AddField(
            model_name='eachquestion',
            name='question',
            field=models.TextField(default='Question', max_length=400),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.EachQuestion'),
        ),
    ]
