# Generated by Django 3.0.3 on 2020-06-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200604_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eachquestion',
            name='correctAns',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
