# Generated by Django 3.0.3 on 2020-06-04 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0007_auto_20200604_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Questions')),
            ],
        ),
    ]
