# Generated by Django 3.0.3 on 2020-06-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_currentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='title',
        ),
        migrations.DeleteModel(
            name='CurrentUser',
        ),
        migrations.DeleteModel(
            name='EachQuestion',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
