# Generated by Django 3.0.3 on 2020-06-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200627_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='links',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
