# Generated by Django 3.0.3 on 2020-06-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20200627_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('IT', 'IT'), ('CIVIL', 'CIVIL'), ('ECM', 'ECM')], default='CSE', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('IT', 'IT'), ('CIVIL', 'CIVIL'), ('ECM', 'ECM')], default='CSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='links',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
