# Generated by Django 3.0.3 on 2020-06-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200629_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='branch',
            field=models.CharField(choices=[('GlOBAL', 'GLOBAL'), ('CSE', 'CSE'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('IT', 'IT'), ('CIVIL', 'CIVIL'), ('ECM', 'ECM')], default='GlOBAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.CharField(choices=[('All Years', 'All Years'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='All Years', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('All Years', 'All Years'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=20),
        ),
    ]
