# Generated by Django 3.0.3 on 2020-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20200630_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sections',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='All Years', max_length=20),
        ),
    ]
