# Generated by Django 3.0.3 on 2020-07-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20200701_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='branch',
            field=models.CharField(choices=[('GLOBAL', 'GLOBAL'), ('CSE', 'CSE'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('IT', 'IT'), ('CIVIL', 'CIVIL'), ('ECM', 'ECM')], default='GLOBAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('GLOBAL', 'GLOBAL'), ('CSE', 'CSE'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('IT', 'IT'), ('CIVIL', 'CIVIL'), ('ECM', 'ECM')], default='CSE', max_length=20),
        ),
    ]
